"""Fix foreign key to API table

Revision ID: c4adf399d779
Revises: db6b4ecde879
Create Date: 2025-05-13 18:46:49.411212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4adf399d779'
down_revision = 'db6b4ecde879'
branch_labels = None
depends_on = None


def upgrade():
    # Create the new paymob_order table
    op.create_table('paymob_order',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('order_id', sa.Integer(), nullable=False),
        sa.Column('api_id', sa.Integer(), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['api_id'], ['api.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('order_id')
    )

    # Fix purchased_api.api_key to match the model (String(255), not nullable)
    with op.batch_alter_table('purchased_api', schema=None) as batch_op:
        batch_op.alter_column('transaction_id',
            existing_type=sa.VARCHAR(length=120),
            nullable=False)
        batch_op.alter_column('api_key',
            existing_type=sa.VARCHAR(length=64),
            type_=sa.String(length=255),
            nullable=False)

    # REMOVE these lines if you're not actually removing these:
    # - batch_op.drop_column('timestamp')
    # - op.drop_table('product')
    # - batch_op.drop_column('api_key') in API
    # - altering name/price to nullable=True in API


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchased_api', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DATETIME(), nullable=True))
        batch_op.alter_column('api_key',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('transaction_id',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)

    with op.batch_alter_table('api', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_key', sa.TEXT(), nullable=True))
        batch_op.alter_column('price',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    op.create_table('product',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('price', sa.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('paymob_order')
    # ### end Alembic commands ###
